# Generated by Django 4.2.5 on 2023-11-05 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toyapp', '0004_age_brand_category_subcategory_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
